'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { Badge, Button, Card, CardBody } from '@/components/ui';
import { supabase } from '@/lib/supabase/client';
import { Batch, CorrectOption, Question, questionOptions } from '@/types';
import { CheckCircle, ChevronLeft, ChevronRight } from 'lucide-react';
export default function BatchTestPage() { const { id } = useParams<{ id: string }>(); const [batch, setBatch] = useState<Batch | null>(null); const [questions, setQuestions] = useState<Question[]>([]); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Record<string, CorrectOption>>({}); const [submitted, setSubmitted] = useState(false); useEffect(() => { if (!id) return; void Promise.all([supabase.from('batches').select('*').eq('id', id).single(), supabase.from('questions').select('*, category:categories(*)').eq('batch_id', id).eq('is_active', true).order('created_at')]).then(([batchResult, questionResult]) => { setBatch(batchResult.data as Batch | null); setQuestions((questionResult.data ?? []) as Question[]); }); }, [id]); if (!batch) return <p className="p-6">Loading…</p>; if (!questions.length) return <main className="p-6"><h1 className="text-2xl font-bold">{batch.batch_name}</h1><p className="mt-3">No active questions are available in this batch.</p></main>; const question = questions[index]; const score = questions.reduce((total, item) => total + (answers[item.id] === item.correct_option ? 1 : 0), 0); if (submitted) return <main className="mx-auto max-w-xl p-6"><Card><CardBody className="p-8 text-center"><CheckCircle className="mx-auto h-12 w-12 text-green-600" /><h1 className="mt-3 text-3xl font-bold">Test complete</h1><p className="mt-3">You answered {score} of {questions.length} correctly.</p><Link href="/mock-tests"><Button className="mt-6">Back to Batches</Button></Link></CardBody></Card></main>; return <main className="mx-auto max-w-3xl p-6"><div className="mb-5 flex justify-between"><Badge>{question.category?.name ?? 'Question'}</Badge><span>{index + 1} / {questions.length}</span></div><Card><CardBody className="p-6"><h1 className="text-xl font-semibold">{question.question_text}</h1><div className="mt-6 space-y-3">{questionOptions(question).map((option) => <button key={option.key} onClick={() => setAnswers((all) => ({ ...all, [question.id]: option.key }))} className={`block w-full rounded border p-3 text-left ${answers[question.id] === option.key ? 'border-blue-600 bg-blue-50' : ''}`}><strong>{option.key}.</strong> {option.text}</button>)}</div><div className="mt-6 flex justify-between"><Button variant="outline" disabled={index === 0} onClick={() => setIndex((current) => current - 1)}><ChevronLeft />Previous</Button>{index === questions.length - 1 ? <Button onClick={() => setSubmitted(true)}>Submit</Button> : <Button onClick={() => setIndex((current) => current + 1)}>Next<ChevronRight /></Button>}</div></CardBody></Card></main>; }
