-- Production subscription architecture for Terrah Qbank.
-- Convention: a NULL duration or limit means unlimited. Values are never inferred
-- in application code; read the entitlement columns from plans instead.

begin;

alter table public.plans
  add column if not exists slug text,
  add column if not exists description text,
  add column if not exists duration_days integer,
  add column if not exists daily_question_limit integer,
  add column if not exists monthly_mock_test_limit integer,
  add column if not exists lifetime_question_limit integer,
  add column if not exists allow_result_history boolean not null default false,
  add column if not exists allow_pdf_download boolean not null default false,
  add column if not exists allow_analytics boolean not null default false,
  add column if not exists allow_bookmarks boolean not null default false,
  add column if not exists allow_review_answers boolean not null default false,
  add column if not exists allow_performance_dashboard boolean not null default false,
  add column if not exists priority_support boolean not null default false,
  add column if not exists updated_at timestamptz not null default now();

alter table public.plans
  alter column price type numeric(10,2) using price::numeric(10,2),
  alter column price set default 0,
  alter column price set not null;

-- Existing installations used a features JSONB field. It is retained so this
-- migration is non-destructive, but entitlement decisions must use the columns above.
update public.plans
set slug = lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g'))
where slug is null;

alter table public.plans alter column slug set not null;
create unique index if not exists plans_slug_key on public.plans (slug);
alter table public.plans drop constraint if exists plans_price_nonnegative;
alter table public.plans add constraint plans_price_nonnegative check (price >= 0);
alter table public.plans drop constraint if exists plans_duration_days_positive;
alter table public.plans add constraint plans_duration_days_positive check (duration_days is null or duration_days > 0);
alter table public.plans drop constraint if exists plans_daily_question_limit_nonnegative;
alter table public.plans add constraint plans_daily_question_limit_nonnegative check (daily_question_limit is null or daily_question_limit >= 0);
alter table public.plans drop constraint if exists plans_monthly_mock_test_limit_nonnegative;
alter table public.plans add constraint plans_monthly_mock_test_limit_nonnegative check (monthly_mock_test_limit is null or monthly_mock_test_limit >= 0);
alter table public.plans drop constraint if exists plans_lifetime_question_limit_nonnegative;
alter table public.plans add constraint plans_lifetime_question_limit_nonnegative check (lifetime_question_limit is null or lifetime_question_limit >= 0);

-- The existing subscriptions table is kept as the subscription history. A user has
-- at most one active row; expiry moves that row to expired before FREE is activated.
alter table public.subscriptions
  add column if not exists starts_at timestamptz not null default now(),
  add column if not exists expires_at timestamptz,
  add column if not exists cancelled_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.subscriptions alter column status set default 'active';
create unique index if not exists subscriptions_one_active_per_user_idx
  on public.subscriptions (user_id) where status = 'active';
create index if not exists subscriptions_user_status_expires_idx
  on public.subscriptions (user_id, status, expires_at);

create table if not exists public.user_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subscription_id bigint not null references public.subscriptions(id) on delete cascade,
  questions_today integer not null default 0 check (questions_today >= 0),
  tests_this_month integer not null default 0 check (tests_this_month >= 0),
  free_questions_used integer not null default 0 check (free_questions_used >= 0),
  last_daily_reset date not null default current_date,
  subscription_started_at timestamptz not null,
  subscription_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create index if not exists user_usage_subscription_id_idx on public.user_usage (subscription_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists plans_set_updated_at on public.plans;
create trigger plans_set_updated_at before update on public.plans
for each row execute function public.set_updated_at();

drop trigger if exists subscriptions_set_updated_at on public.subscriptions;
create trigger subscriptions_set_updated_at before update on public.subscriptions
for each row execute function public.set_updated_at();

drop trigger if exists user_usage_set_updated_at on public.user_usage;
create trigger user_usage_set_updated_at before update on public.user_usage
for each row execute function public.set_updated_at();

-- Seed data is repeated here so a fresh migration creates usable entitlements.
insert into public.plans (
  name, slug, description, price, duration_days, daily_question_limit,
  monthly_mock_test_limit, lifetime_question_limit, allow_result_history,
  allow_pdf_download, allow_analytics, allow_bookmarks, allow_review_answers,
  allow_performance_dashboard, priority_support, is_active
) values
  ('FREE', 'free', 'Free practice access', 0, null, 0, 0, 100, false, false, false, false, true, false, false, true),
  ('STARTER', 'starter', 'Starter monthly preparation plan', 99, 30, 50, 15, null, true, false, true, true, true, false, false, true),
  ('PRO', 'pro', 'Pro monthly preparation plan', 299, 30, 100, 30, null, true, true, true, true, true, true, false, true),
  ('PREMIUM', 'premium', 'Premium quarterly preparation plan', 599, 90, 250, 100, null, true, true, true, true, true, true, true, true),
  ('ELITE', 'elite', 'Elite annual unlimited preparation plan', 1499, 365, null, null, null, true, true, true, true, true, true, true, true)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, price = excluded.price,
  duration_days = excluded.duration_days, daily_question_limit = excluded.daily_question_limit,
  monthly_mock_test_limit = excluded.monthly_mock_test_limit,
  lifetime_question_limit = excluded.lifetime_question_limit,
  allow_result_history = excluded.allow_result_history,
  allow_pdf_download = excluded.allow_pdf_download, allow_analytics = excluded.allow_analytics,
  allow_bookmarks = excluded.allow_bookmarks, allow_review_answers = excluded.allow_review_answers,
  allow_performance_dashboard = excluded.allow_performance_dashboard,
  priority_support = excluded.priority_support, is_active = excluded.is_active;

create or replace function public.create_free_subscription_for_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_subscription public.subscriptions;
begin
  insert into public.subscriptions (user_id, plan_id, status, starts_at, expires_at)
  select new.id, p.id, 'active', now(), null
  from public.plans p
  where p.slug = 'free'
  on conflict do nothing
  returning * into v_subscription;

  if v_subscription.id is not null then
    insert into public.user_usage (user_id, subscription_id, subscription_started_at, subscription_expires_at)
    values (new.id, v_subscription.id, v_subscription.starts_at, v_subscription.expires_at)
    on conflict (user_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_create_free_subscription on public.profiles;
create trigger profiles_create_free_subscription
after insert on public.profiles
for each row execute function public.create_free_subscription_for_profile();

-- Backfill the FREE entitlement for profiles created before this migration.
insert into public.subscriptions (user_id, plan_id, status, starts_at, expires_at)
select pr.id, p.id, 'active', now(), null
from public.profiles pr
cross join public.plans p
where p.slug = 'free'
  and not exists (select 1 from public.subscriptions s where s.user_id = pr.id and s.status = 'active');

insert into public.user_usage (user_id, subscription_id, subscription_started_at, subscription_expires_at)
select s.user_id, s.id, s.starts_at, s.expires_at
from public.subscriptions s
where s.status = 'active'
on conflict (user_id) do nothing;

-- Call this from the payment webhook with the service role after marking the old
-- subscription non-active. It makes renewal resets atomic and database-driven.
create or replace function public.activate_subscription(
  p_user_id uuid,
  p_plan_slug text,
  p_started_at timestamptz default now()
)
returns public.subscriptions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan public.plans;
  v_subscription public.subscriptions;
begin
  select * into v_plan from public.plans where slug = p_plan_slug and is_active;
  if not found then raise exception 'Active plan % does not exist', p_plan_slug using errcode = 'P0001'; end if;

  update public.subscriptions
  set status = case when status = 'active' then 'cancelled' else status end,
      cancelled_at = case when status = 'active' then now() else cancelled_at end
  where user_id = p_user_id and status = 'active';

  insert into public.subscriptions (user_id, plan_id, status, starts_at, expires_at)
  values (p_user_id, v_plan.id, 'active', p_started_at,
          case when v_plan.duration_days is null then null else p_started_at + make_interval(days => v_plan.duration_days) end)
  returning * into v_subscription;

  insert into public.user_usage (user_id, subscription_id, questions_today, tests_this_month,
                                 free_questions_used, last_daily_reset, subscription_started_at, subscription_expires_at)
  values (p_user_id, v_subscription.id, 0, 0, 0, current_date, v_subscription.starts_at, v_subscription.expires_at)
  on conflict (user_id) do update set subscription_id = excluded.subscription_id,
    questions_today = 0, tests_this_month = 0, last_daily_reset = current_date,
    subscription_started_at = excluded.subscription_started_at,
    subscription_expires_at = excluded.subscription_expires_at;
  return v_subscription;
end;
$$;

-- Schedule this function with Supabase Cron, or call it from a trusted scheduled job.
create or replace function public.expire_due_subscriptions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare v_count integer;
begin
  with expired as (
    update public.subscriptions set status = 'expired'
    where status = 'active' and expires_at is not null and expires_at <= now()
    returning user_id
  )
  select count(*) into v_count from expired;

  -- Each affected profile receives a fresh FREE subscription and reset usage row.
  perform public.activate_subscription(pr.id, 'free')
  from public.profiles pr
  where not exists (select 1 from public.subscriptions s where s.user_id = pr.id and s.status = 'active');
  return v_count;
end;
$$;

-- Refreshes daily counters at login and returns the user's current entitlement.
create or replace function public.refresh_my_usage()
returns table (
  plan_slug text, daily_question_limit integer, monthly_mock_test_limit integer,
  lifetime_question_limit integer, questions_today integer, tests_this_month integer,
  free_questions_used integer, subscription_expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if exists (
    select 1 from public.subscriptions
    where user_id = auth.uid() and status = 'active'
      and expires_at is not null and expires_at <= now()
  ) then
    perform public.activate_subscription(auth.uid(), 'free');
  end if;
  update public.user_usage set questions_today = 0, last_daily_reset = current_date
  where user_id = auth.uid() and last_daily_reset < current_date;
  return query
  select p.slug, p.daily_question_limit, p.monthly_mock_test_limit, p.lifetime_question_limit,
         u.questions_today, u.tests_this_month, u.free_questions_used, u.subscription_expires_at
  from public.user_usage u
  join public.subscriptions s on s.id = u.subscription_id and s.status = 'active'
  join public.plans p on p.id = s.plan_id
  where u.user_id = auth.uid();
end;
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role::text = 'admin') $$;

alter table public.plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.user_usage enable row level security;

drop policy if exists plans_read_active on public.plans;
create policy plans_read_active on public.plans for select using (is_active or public.is_admin());
drop policy if exists plans_admin_manage on public.plans;
create policy plans_admin_manage on public.plans for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists subscriptions_read_own_or_admin on public.subscriptions;
create policy subscriptions_read_own_or_admin on public.subscriptions for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists subscriptions_admin_manage on public.subscriptions;
create policy subscriptions_admin_manage on public.subscriptions for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists usage_read_own_or_admin on public.user_usage;
create policy usage_read_own_or_admin on public.user_usage for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists usage_admin_manage on public.user_usage;
create policy usage_admin_manage on public.user_usage for all using (public.is_admin()) with check (public.is_admin());

revoke all on function public.activate_subscription(uuid, text, timestamptz) from public;
revoke all on function public.expire_due_subscriptions() from public;
grant execute on function public.refresh_my_usage() to authenticated;

commit;
